config/routes.rb
Rails.application.routes.draw do
  get 'profile', to: 'users#show'
  devise_for :users

  # resources :bookings, only: [:destroy, :edit] do
  #   collection do
  #     get 'users/bookings', to: 'bookings#index'
  #   end
  # end
  resources :bookings, only: [:index, :destroy, :edit, :update]

  get '/bookings/:id/validate', to: 'bookings#accept', as: 'booking_accept'
  get '/bookings/:id/cancelled', to: 'bookings#cancelled', as: 'booking_refuse'

  resources :products do
    resources :reviews, only: [:new, :create]
    resources :bookings, only: [:new, :create]
  end

  get '/myproducts', to: 'pages#product', as: 'my_products'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :product
  belongs_to :user
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :status, presence: true
  validates :description, presence: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only:[:edit, :show, :update, :destroy, :accept, :cancelled]


  def show
  end

  def index
    user = current_user
    @bookings_done = current_user.bookings
    @bookings_receive = current_user.products_bookings
  end

  def new
    @booking = Booking.new
  end

  def create
    
    if booking_params['start_date'] > booking_params['end_date'] || booking_params['end_date'].blank? ||booking_params['end_date'] < Time.now
      flash[:alert] = "Dates invalides"
      return redirect_to product_path(Product.find(booking_params[:product_id]))
    end 

    user = current_user
    @booking = user.bookings.new(booking_params)
      if @booking.save
        flash[:notice] = "La reservation s'est bien passé"
        redirect_to bookings_path
      else
        flash[:alert] = "Erreur lors de la reservation "
        return redirect_to product_path(Product.find(booking_params[:product_id]))
      end
  end


  def edit
    @product = Product.find(@booking.product_id)
  end

  def update
    @booking.update(booking_params)
    flash[:notice] = "Booking edited"
    redirect_to bookings_path
  end

  def destroy
    @booking.destroy
    flash[:notice] = "Reservation supprimer"
    redirect_to bookings_path
  end

  def accept
    @booking.status = 'accepté'
    @booking.save
    redirect_to bookings_path
  end

  def cancelled
    @booking.status = 'refusé'
    @booking.save
    redirect_to bookings_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(
                                    :start_date,
                                    :end_date,
                                    :product_id,
                                    :user_id,
                                    :status,
                                    :description
                                    )
  end

end

app/views/bookings/edit.html.erb
<%= simple_form_for [@booking] do |f|%>
  <%= f.input :status %>
  <%= f.submit %><br>
<% end %> 

app/views/bookings/index.html.erb
<div class='container'>
  <div class="row">
    <h3> Demande de location envoyé </h3>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>Mannequin</th>
          <th>Motif</th>
          <th>Date de début</th>
          <th>Date de fin</th>
          <th>Status</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @bookings_done.each_with_index do |booking, index| %>
          <tr>
            <th scope="row"><%= index + 1 %></th>
            <td>
              <%= link_to product_path(booking.product) do %>
                <%= booking.product.first_name %> 
                <%= booking.product.last_name %>
              <% end %>
            </td>
            <td><%= booking.description %></td>
            <td><%= booking.start_date %></td>
            <td><%= booking.end_date %></td>
            <td><%= booking.status.capitalize %></td>
            <td>
              <%= link_to 'Supprimer', booking_path(booking), method: :delete %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class='row'>
    <h3> Demande de location reçu </h3>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>Mannequin</th>
          <th>Motif</th>
          <th>Date de début</th>
          <th>Date de fin</th>
          <th>Status</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @bookings_receive.each_with_index do |booking, index| %>
          <tr>
            <th scope="row"><%= index + 1 %></th>
            <td>
              <%= link_to product_path(booking.product) do %>
                <%= booking.product.first_name %> 
                <%= booking.product.last_name %>
              <% end %>
            </td>
            <td><%= booking.description %></td>
            <td><%= booking.start_date %></td>
            <td><%= booking.end_date %></td>
            <td><%= booking.status.capitalize %></td>
            <td>
              <% if booking.status.upcase == 'EN ATTENTE'%>
                <%= link_to 'Accepter |', booking_accept_path(booking)%>
                <%= link_to 'Refuser', booking_refuse_path(booking) %>
              <% else %>
                <%= link_to 'Supprimer', booking_path(booking), method: :delete %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/bookings/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.description %></p>
<%= link_to 'Modifier', edit_task_path %> / 
<%= link_to 'Retour sur la liste', tasks_path %> / 
<%= link_to 'Supprimer', task_path, method: :delete%>