config/routes.rb
Rails.application.routes.draw do
  get 'profile', to: 'users#show'
  devise_for :users

  # resources :bookings, only: [:destroy, :edit] do
  #   collection do
  #     get 'users/bookings', to: 'bookings#index'
  #   end
  # end
  resources :bookings, only: [:index, :destroy, :edit, :update]

  get '/bookings/:id/validate', to: 'bookings#accept', as: 'booking_accept'
  get '/bookings/:id/cancelled', to: 'bookings#cancelled', as: 'booking_refuse'

  resources :products do
    resources :reviews, only: [:new, :create]
    resources :bookings, only: [:new, :create]
  end

  get '/myproducts', to: 'pages#product', as: 'my_products'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(227, 17, 97, 0.31) 0%, rgba(0, 0, 0, 0.42) 50%), url(<%= image_path "banner.jpg" %>);">
  <div class="banner-content">
    <h1>Machos</h1>
    <p>Des nanas proche de chez vous</p>
      <form class="form-inline" action='/products' method='get' id='form-banner'>
        <select class="form-control" id="sel1" name='skill_id' style='width: 200px;'>
          <option value ='' >Spécialité ?</option>
          <% @skills.each do |skill| %>
            <option value ='<%= skill.id %>'><%= skill.name.capitalize %></option>
          <% end %>s
        </select>
        <div class="input-group mb-2 mr-sm-2 mb-sm-0">
          <input type="text" class="form-control" name='city' id='city' placeholder="Ville">
          <input type="hidden" name='lng' id='lng'>
          <input type="hidden" name='lat' id ='lat'>
        </div>
        <button type="submit" class="btn btn-danger">Voir nos models</button>
      </form>
  </div>
</div>

app/views/shared/_card.html.erb
<div class='card-wrapper'>
  <div class='main-window' id='main-window'>
    <%= link_to product_path(product) do %>
      <div class='user-image' style='background: url(<%= cl_image_path product.photo if !product.photo.url.nil? %>);'>
        <div class='username'><%= "#{product.first_name} #{product.last_name}" %></div>
        <div class='price username'><%= "#{product.price} €" %></div>
      </div>
    <% end %>
    <div class='user-info'>
      <div class='quote'>"
        <%= product.description.first(70) %>
        <%= "..." if product.description.length > 70 %>"
      </div>
    </div>

    <div class='social-info'>
      <div class='social-info-elm-card'>Taille<br><span class='lg'><%= product.height %></span></div>
      <div class='social-info-elm-card'>Poids<br><span class='lg'><%= product.weight %></span></div>
      <div class='social-info-elm-card'>Ville<br><span class='lg' style='<%= 'font-size:13px' if  product.city.length> 7 %>'><%= product.city.first(7) %></span></div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "macho.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Poster une annonce", new_product_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Tous les modèles", products_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.avatar.url.blank? %>
            <%= image_tag "http://www.jobsenboite.com/images/avatar/default-avatar.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% else %>
            <%= image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to profile_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: " Mon compte") %>
              <% end %>
            </li>
            <li>
              <%= link_to bookings_path do %>
                <i class="fa fa-calendar-o"></i>  <%= t(".profile", default: " Mes reservations") %>
              <% end %>
            </li>
            <li>
              <%= link_to my_products_path do %>
                <i class="fa fa-female"></i>  <%= t(".profile", default: " Mes annonces") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-user-times"></i>  <%= t(".profile", default: " Déconnexion") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: " Login "), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_review.html.erb
<div class="message">
  <% if review.user.avatar.url.blank? %>
    <%= image_tag "http://www.jobsenboite.com/images/avatar/default-avatar.png", class: "avatar-large" %>
  <% else %>
    <%= image_tag review.user.avatar, class: "avatar-large" %>
  <% end %>

  <div class="message-body">
    <p><%= review.content %></p>
  </div>
  <div class="message-status">
    <p class="price">
      <% 5.times do |i|  %>
        <%= review.rating - (i) > 0 ? '<i class="fa fa-star" aria-hidden="true"></i>'.html_safe : '<i class="fa fa-star-o" aria-hidden="true"></i>'.html_safe %>
      <%end %>
    </p>
  </div>
</div>

app/views/shared/_service.html.erb
<div class="block-service">
  <i class="fa <%= service[:icon] %> block-service__icon" aria-hidden="true"></i>
  <span class="block-service__label"><%= service[:title] %></span>
  <p class="block-service__descr"><%= service[:content] %></p>
</div>